; PlatformIO Project Configuration File
;
; Proteus 仿真：STM32F103C8 内部 HSI 8MHz，无外部晶振
; 请使用 build 出的 firmware.bin / firmware.hex 加载到 U1

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
board_build.f_cpu = 8000000L
build_flags =
	-D SERIAL_UART_INSTANCE=1
	-D HSE_VALUE=8000000U
lib_deps =
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
